// Pre-render the repo's design docs (../../docs/*.md) into a single bundled data module the docs page
// imports — so the documentation lives ON the site (rendered HTML + a search index), never a redirect
// back to GitHub. Runs in Node at build time (and via `predev`); marked stays a build-time dep, so the
// client ships plain HTML + text, no markdown parser. Em dashes are normalized to hyphens in the
// rendered output (site presentation only; the source .md files are left canonical).
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const here = fileURLToPath(new URL('.', import.meta.url));
const docsDir = fileURLToPath(new URL('../../docs/', import.meta.url));

// Curated grouping + order + short sidebar label. Mirrors docs/README.md.
const GROUPS = [
  { name: 'Core database', docs: [
    ['design-spec', 'VFS & envelope spec'],
    ['bundle-format', 'Bundle format'],
    ['dek-rotation-design', 'DEK rotation'],
    ['convenience-tier-design', 'Device-key unlock'],
  ]},
  { name: 'Sync & transport', docs: [
    ['sync-epoch-design', 'Anti-rollback epochs'],
    ['transport-design', 'Relay transport'],
    ['relay-auth-design', 'Relay authorization'],
  ]},
  { name: 'Data custody', docs: [
    ['data-custody-protocol', 'Custody protocol'],
    ['vault-signing-design', 'Vault signing'],
    ['requester-auth-design', 'Requester auth'],
    ['grant-token-design', 'Grant tokens'],
  ]},
  { name: 'Device trust', docs: [
    ['device-trust-design', 'Device trust'],
  ]},
  { name: 'Security & assurance', docs: [
    ['audit-readiness', 'Audit readiness'],
    ['BUILD-NOTES', 'Guarantee ledger'],
    ['security-review', 'Security review'],
    ['adversarial-review', 'Adversarial review'],
    ['supply-chain', 'Supply chain'],
  ]},
];

const deEm = (s) => s.replace(/—/g, '-');            // em dash -> hyphen (presentation only)
const stripTags = (h) => h.replace(/<[^>]+>/g, ' ')
  .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&#39;/g, "'").replace(/&quot;/g, '"')
  .replace(/\s+/g, ' ').trim();
const slugify = (t) => t.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60);

function parseFrontMatter(md) {
  if (!md.startsWith('---')) return { meta: {}, body: md };
  const end = md.indexOf('\n---', 3);
  if (end === -1) return { meta: {}, body: md };
  const block = md.slice(3, end);
  const body = md.slice(end + 4).replace(/^\s*\n/, '');
  const meta = {};
  for (const line of block.split('\n')) {
    const m = line.match(/^([a-zA-Z0-9_-]+):\s*(.*)$/);
    if (m && !/^\s/.test(line)) meta[m[1]] = m[2].replace(/\s+#.*$/, '').trim();
  }
  return { meta, body };
}

function render(slug, label) {
  const raw = readFileSync(docsDir + slug + '.md', 'utf8');
  const { meta, body } = parseFrontMatter(raw);
  // Title: front-matter title, else first H1, else the sidebar label.
  let title = meta.title;
  if (!title) { const h1 = body.match(/^#\s+(.+)$/m); title = h1 ? h1[1] : label; }
  title = deEm(title).trim();
  const status = meta.status ? deEm(meta.status) : '';

  marked.setOptions({ gfm: true, breaks: false });
  let html = marked.parse(body);

  // Add stable ids to h2/h3 and collect a table of contents.
  const headings = [];
  const seen = new Set();
  html = html.replace(/<h([23])>([\s\S]*?)<\/h\1>/g, (_, lvl, inner) => {
    const text = stripTags(inner);
    let id = slugify(text) || 'sec';
    let n = 2; const base = id; while (seen.has(id)) id = `${base}-${n++}`;
    seen.add(id);
    headings.push({ id, text: deEm(text), level: Number(lvl) });
    return `<h${lvl} id="${id}">${inner}</h${lvl}>`;
  });
  html = deEm(html);
  const text = stripTags(html);
  return { slug, label, title, status, group: '', html, headings, text };
}

const docs = {};
const groupsOut = GROUPS.map((g) => ({
  name: g.name,
  docs: g.docs.map(([slug, label]) => {
    const d = render(slug, label);
    d.group = g.name;
    docs[slug] = d;
    return { slug, label };
  }),
}));

// Rewrite intra-doc links (`relay-auth-design.md`, `./docs/foo.md#x`) to in-site hash routes so the
// documentation stays on the site. Links to docs we don't render, or external URLs, are left alone.
const known = new Set(Object.keys(docs));
for (const slug of known) {
  docs[slug].html = docs[slug].html.replace(/href="([^"]+)"/g, (m, href) => {
    const hit = href.match(/^(?:\.\/)?(?:docs\/)?([\w.-]+)\.md(#[^"]*)?$/);
    if (hit && known.has(hit[1])) return `href="#${hit[1]}"`;
    return m;
  });
}

const out =
  `// AUTO-GENERATED by build-docs.mjs — do not edit. Rendered from ../../docs/*.md at build time.\n` +
  `export const GROUPS = ${JSON.stringify(groupsOut)};\n` +
  `export const DOCS = ${JSON.stringify(docs)};\n`;

writeFileSync(here + 'docs-data.js', out);
const n = Object.keys(docs).length;
const bytes = Buffer.byteLength(out);
console.log(`[docs] rendered ${n} docs -> docs-data.js (${(bytes / 1024).toFixed(0)} kB)`);
