/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const add_passkey: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const add_recovery: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const enroll: (a: number, b: number) => any;
export const export_db: (a: number, b: number, c: number, d: number) => any;
export const gen_recovery: () => [number, number, number, number];
export const import_db_image: (a: number, b: number) => any;
export const list_methods: (a: number, b: number) => [number, number, number, number];
export const remove_method: (a: number, b: number, c: number) => [number, number, number, number];
export const run_tests: () => any;
export const unlock: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const unlock_recovery: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const rust_sqlite_wasm_abort: () => void;
export const rust_sqlite_wasm_assert_fail: (a: number, b: number, c: number, d: number) => void;
export const rust_sqlite_wasm_calloc: (a: number, b: number) => number;
export const rust_sqlite_wasm_free: (a: number) => void;
export const rust_sqlite_wasm_getentropy: (a: number, b: number) => number;
export const rust_sqlite_wasm_localtime: (a: number) => number;
export const rust_sqlite_wasm_malloc: (a: number) => number;
export const rust_sqlite_wasm_realloc: (a: number, b: number) => number;
export const sqlite3_os_end: () => number;
export const sqlite3_os_init: () => number;
export const wasm_bindgen__convert__closures_____invoke__ha22148a4a7c1d5ff: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h44475d2d48e3e63e: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
